backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "news"
    label: "الأخبار"
    folder: "content/news"
    create: true
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "الكاتب", name: "author", widget: "string", default: "gsome160@gmail.com"}
      - {label: "المحتوى", name: "body", widget: "markdown"}
